In [146]:
import numpy as np
import pandas as pd 
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup as bs
import requests

1. Scrape the details of most viewed videos on YouTube from Wikipedia:

Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date 

E) Views

In [2]:
page = requests.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
soup = bs(page.text,'html.parser')

tables = pd.read_html(page.text)
tables

[    0                                                  1
 0 NaN  This article needs additional citations for ve...,
     0                                                  1
 0 NaN  This section possibly contains original resear...,
                     No.                                       Video name  \
 0                    1.                           "Baby Shark Dance"[22]
 1                    2.                                  "Despacito"[24]
 2                    3.                       "Johny Johny Yes Papa"[25]
 3                    4.                               "Shape of You"[26]
 4                    5.                              "See You Again"[27]
 5                    6.   "Masha and the Bear – Recipe for Disaster"[30]
 6                    7.                                  "Bath Song"[31]
 7                    8.  "Learning Colors – Colorful Eggs on a Farm"[32]
 8                    9.                                "Uptown Funk"[33]
 9                   10.                              "Gangnam Style"[34]
 10                  11.                "Phonics Song with Two Words"[36]
 11                  12.                                      "Sugar"[37]
 12                  13.                             "Dame Tu Cosita"[38]
 13                  14.                                      "Sorry"[39]
 14                  15.                                       "Roar"[40]
 15                  16.                             "Counting Stars"[41]
 16                  17.                          "Thinking Out Loud"[42]
 17                  18.                          "Wheels on the Bus"[43]
 18                  19.                                 "Dark Horse"[44]
 19                  20.                                      "Faded"[45]
 20                  21.                               "Shake It Off"[46]
 21                  22.                             "Girls Like You"[47]
 22                  23.                                    "Lean On"[48]
 23                  24.                                   "Bailando"[49]
 24                  25.                                 "Let Her Go"[50]
 25                  26.                                   "Mi Gente"[51]
 26                  27.                                    "Perfect"[52]
 27                  28.           "Waka Waka (This Time for Africa)"[53]
 28                  29.                                     "Axel F"[54]
 29                  30.                                      "Hello"[55]
 30  As of July 11, 2021                              As of July 11, 2021

                           Uploader     Views (billions)          Upload date  \
 0   Pinkfong Kids' Songs & Stories                 8.95        June 17, 2016
 1                       Luis Fonsi                 7.44     January 12, 2017
 2                      LooLoo Kids                 5.54      October 8, 2016
 3                       Ed Sheeran                 5.38     January 30, 2017
 4                      Wiz Khalifa                 5.17        April 6, 2015
 5                       Get Movies                 4.44     January 31, 2012
 6       Cocomelon – Nursery Rhymes                 4.29          May 2, 2018
 7                      Miroshka TV                 4.25    February 27, 2018
 8                      Mark Ronson                 4.22    November 19, 2014
 9                              Psy                 4.11        July 15, 2012
 10                       ChuChu TV                 3.98        March 6, 2014
 11                        Maroon 5                 3.50     January 14, 2015
 12                       El Chombo                 3.45        April 5, 2018
 13                   Justin Bieber                 3.45     October 22, 2015
 14                      Katy Perry                 3.38    September 5, 2013
 15                     OneRepublic                 3.34         May 31, 2013
 16                      Ed Sheeran                 3.29      October 7, 2014
 17      Cocomelon – Nursery Rhymes                 3.15         May 24, 2018
 18                      Katy Perry                 3.10    February 20, 2014
 19                     Alan Walker                 3.10     December 3, 2015
 20                    Taylor Swift                 3.07      August 18, 2014
 21                        Maroon 5                 3.07         May 31, 2018
 22                     Major Lazer                 3.06       March 22, 2015
 23                Enrique Iglesias                 3.06       April 11, 2014
 24                       Passenger                 3.02        July 25, 2012
 25                        J Balvin                 2.94        June 29, 2017
 26                      Ed Sheeran                 2.89     November 9, 2017
 27                         Shakira                 2.88         June 4, 2010
 28                      Crazy Frog                 2.87        June 16, 2009
 29                           Adele                 2.85     October 22, 2015
 30             As of July 11, 2021  As of July 11, 2021  As of July 11, 2021

                    Note           Unnamed: 6
 0                   [B]                  NaN
 1                   [C]                  NaN
 2                   [D]                  NaN
 3                   [E]                  NaN
 4                   [F]                  NaN
 5                   [G]                  NaN
 6                   [H]                  NaN
 7                   [I]                  NaN
 8                   [J]                  NaN
 9                   [K]                  NaN
 10                  NaN                  NaN
 11                  NaN                  NaN
 12                  NaN                  NaN
 13                  NaN                  NaN
 14                  NaN                  NaN
 15                  NaN                  NaN
 16                  NaN                  NaN
 17                  NaN                  NaN
 18                  NaN                  NaN
 19                  NaN                  NaN
 20                  NaN                  NaN
 21                  NaN                  NaN
 22                  NaN                  NaN
 23                  NaN                  NaN
 24                  NaN                  NaN
 25                  NaN                  NaN
 26                  NaN                  NaN
 27                  NaN                  NaN
 28                  NaN                  NaN
 29                  NaN                  NaN
 30  As of July 11, 2021  As of July 11, 2021  ,
     0                                                  1
 0 NaN  This section possibly contains original resear...,
                     Year               Video name               Uploader  \
 0                   2005         "Tarzan Boy"[56]           nailofgilead
 1                   2005      "Me at the zoo"[57]                  jawed
 2                   2005       "Life Goes On"[58]              fhearnoiz
 3                   2005             "guitar"[59]               guitar90
 4                   2005               "Hurt"[60]             beachbuggy
 ..                   ...                      ...                    ...
 99                  2021   "Save Your Tears"[115]             The Weeknd
 100                 2021            "Butter"[116]                    BTS
 101                 2021  "Baarish Ki Jaaye"[117]     DM - Desi Melodies
 102                 2021    Combined views (2021)  Combined views (2021)
 103  As of June 21, 2021      As of June 21, 2021    As of June 21, 2021

         Views (billions)          Upload date                Notes
 0                   0.21     November 2, 2005                  NaN
 1                   0.16       April 23, 2005                  [M]
 2                   0.13   September 22, 2005                  NaN
 3                   0.09    December 20, 2005                  NaN
 4                   0.09    December 12, 2005                  NaN
 ..                   ...                  ...                  ...
 99                  0.41      January 5, 2021                  NaN
 100                 0.38         May 20, 2021                  NaN
 101                 0.36       March 27, 2021                  NaN
 102                 2.33                 [68]                 [68]
 103  As of June 21, 2021  As of June 21, 2021  As of June 21, 2021

 [104 rows x 6 columns],
                             Video name                         Uploader  \
 0               "Baby Shark Dance"[22]  Pinkfong! Kids' Songs & Stories
 1                      "Despacito"[24]                       Luis Fonsi
 2                  "See You Again"[27]                      Wiz Khalifa
 3                 "Gangnam Style"⁂[34]                              Psy
 4                          "Baby"*[85]                    Justin Bieber
 5                    "Bad Romance"[82]                        Lady Gaga
 6          "Charlie Bit My Finger"[73]                            HDCYT
 7             "Evolution of Dance"[66]                   Judson Laipply
 8              "Girlfriend"‡[127][128]                      RCA Records
 9             "Evolution of Dance"[66]                   Judson Laipply
 10     "Music Is My Hot Hot Sex"‡[131]                   CLARUSBARTEL72
 11           "Evolution of Dance"*[66]                   Judson Laipply
 12   "Pokemon Theme Music Video"‡[136]                            Smosh
 13    "Myspace – The Movie"‡[140][141]                           eggtea
 14           "Phony Photo Booth"‡[143]                        mugenized
 15   "The Chronic of Narnia Rap"‡[145]                      youtubedude
 16  "Ronaldinho: Touch of Gold"‡*[147]                       Nikesoccer
 17                  "I/O Brush"‡*[150]                           larfus
 18                 "Me at the zoo"[57]                            jawed
 19                 As of July 12, 2021              As of July 12, 2021

                  Views*          Upload date        Date achieved  \
 0            7037500000        June 17, 2016     November 2, 2020
 1            2993700000     January 12, 2017       August 4, 2017
 2            2894000000        April 6, 2015        July 10, 2017
 3             803700000        July 15, 2012    November 24, 2012
 4             245400000    February 19, 2010        July 16, 2010
 5             178400000    November 24, 2009       April 14, 2010
 6             128900000         May 22, 2007     October 25, 2009
 7             118900000        April 6, 2006          May 2, 2009
 8              92600000    February 27, 2007        July 17, 2008
 9              78400000        April 6, 2006       March 15, 2008
 10             76600000        April 9, 2007        March 1, 2008
 11             10600000        April 6, 2006         May 19, 2006
 12              4300000    November 28, 2005       March 12, 2006
 13              2700000     January 31, 2006    February 18, 2006
 14              3400000     December 1, 2005     January 21, 2006
 15              2300000    December 18, 2005      January 9, 2006
 16               255000     October 21, 2005     October 31, 2005
 17               247000      October 5, 2005     October 29, 2005
 18                    1       April 23, 2005       April 23, 2005
 19  As of July 12, 2021  As of July 12, 2021  As of July 12, 2021

               Days held                  Ref                Notes
 0                   252                  NaN                  NaN
 1                  1186                [118]                  [O]
 2                    25                 [28]                  NaN
 3                  1689                 [35]                  [P]
 4                   862                [119]                  [Q]
 5                    93                [122]                  [R]
 6                   171                [125]                  NaN
 7                   176                [126]                  NaN
 8                   289                [129]                  NaN
 9                   124                [130]                  NaN
 10                   14                [132]                  [S]
 11                  652                [135]                  [T]
 12                   68                [137]                  [U]
 13                   22                [142]                  NaN
 14                   28                [144]                  [V]
 15                   12                [146]                  NaN
 16                   70                [148]                  [W]
 17                    2                [151]                  NaN
 18                    1                [152]                  NaN
 19  As of July 12, 2021  As of July 12, 2021  As of July 12, 2021  ,
    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteYouTube  \
 0                               History Social impact
 1                                              People
 2                                             Current
 3                                              Former
 4                                            Channels
 5                                   Culture andvideos
 6   BookTube BreadTube Charlie Bit My Finger Creat...
 7                                               Lists
 8                                           By decade
 9                                           Criticism
 10                                  Apps and services
 11                                             Events
 12                                   Related articles

    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteYouTube.1  \
 0                               History Social impact
 1   Current Susan Wojcicki (CEO) Lyor Cohen Susann...
 2   Susan Wojcicki (CEO) Lyor Cohen Susanne Daniel...
 3   Steve Chen (Founder) Chad Hurley (Founder) Sal...
 4   Most-subscribed channels Music artists Most-vi...
 5   BookTube BreadTube Charlie Bit My Finger Creat...
 6   BookTube BreadTube Charlie Bit My Finger Creat...
 7   Most-viewed videos 24 hours Arabic music video...
 8   2000s YouTube videos 2010s YouTube videos 2020...
 9   Backdoor advertisement controversy in Korea Ce...
 10       Kids Music Premium (original programming) TV
 11  Awards CNN/YouTube presidential debates Comedy...
 12  API Censorship of YouTube Germany Google Prefe...

    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteYouTube.2
 0                               History Social impact
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ,
          0                                                  1
 0  Current  Susan Wojcicki (CEO) Lyor Cohen Susanne Daniel...
 1   Former  Steve Chen (Founder) Chad Hurley (Founder) Sal...,
                                                    0  \
 0  BookTube BreadTube Charlie Bit My Finger Creat...
 1                                              Lists
 2                                          By decade

                                                    1
 0  BookTube BreadTube Charlie Bit My Finger Creat...
 1  Most-viewed videos 24 hours Arabic music video...
 2  2000s YouTube videos 2010s YouTube videos 2020...  ,
   vteMost popular social media accounts and posts  \
 0                                        Accounts
 1                                Posts and videos

    vteMost popular social media accounts and posts.1
 0  Most-followed Facebook pages Most-followed Ins...
 1  Most-liked Instagram posts Most-liked TikTok v...  ]

In [3]:
most_watched=tables[2]
most_watched.rename(columns={'No.':'Rank','Video name':'Name','Uploader':'Artist'},inplace=True)
most_watched.drop(['Note','Unnamed: 6'],inplace=True,axis=1)
most_watched.drop(most_watched.index[[30]], inplace=True)
most_watched

,Rank,Name,Artist,Views (billions),Upload date
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,8.95,"June 17, 2016"
1,2.,"""Despacito""[24]",Luis Fonsi,7.44,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,5.54,"October 8, 2016"
3,4.,"""Shape of You""[26]",Ed Sheeran,5.38,"January 30, 2017"
4,5.,"""See You Again""[27]",Wiz Khalifa,5.17,"April 6, 2015"
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.44,"January 31, 2012"
6,7.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,4.29,"May 2, 2018"
7,8.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,4.25,"February 27, 2018"
8,9.,"""Uptown Funk""[33]",Mark Ronson,4.22,"November 19, 2014"
9,10.,"""Gangnam Style""[34]",Psy,4.11,"July 15, 2012"
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,3.98,"March 6, 2014"
11,12.,"""Sugar""[37]",Maroon 5,3.50,"January 14, 2015"
12,13.,"""Dame Tu Cosita""[38]",El Chombo,3.45,"April 5, 2018"
13,14.,"""Sorry""[39]",Justin Bieber,3.45,"October 22, 2015"
14,15.,"""Roar""[40]",Katy Perry,3.38,"September 5, 2013"
15,16.,"""Counting Stars""[41]",OneRepublic,3.34,"May 31, 2013"
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.29,"October 7, 2014"
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,3.15,"May 24, 2018"
18,19.,"""Dark Horse""[44]",Katy Perry,3.10,"February 20, 2014"
19,20.,"""Faded""[45]",Alan Walker,3.10,"December 3, 2015"
20,21.,"""Shake It Off""[46]",Taylor Swift,3.07,"August 18, 2014"
21,22.,"""Girls Like You""[47]",Maroon 5,3.07,"May 31, 2018"
22,23.,"""Lean On""[48]",Major Lazer,3.06,"March 22, 2015"
23,24.,"""Bailando""[49]",Enrique Iglesias,3.06,"April 11, 2014"
24,25.,"""Let Her Go""[50]",Passenger,3.02,"July 25, 2012"
25,26.,"""Mi Gente""[51]",J Balvin,2.94,"June 29, 2017"
26,27.,"""Perfect""[52]",Ed Sheeran,2.89,"November 9, 2017"
27,28.,"""Waka Waka (This Time for Africa)""[53]",Shakira,2.88,"June 4, 2010"
28,29.,"""Axel F""[54]",Crazy Frog,2.87,"June 16, 2009"
29,30.,"""Hello""[55]",Adele,2.85,"October 22, 2015"

2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [4]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get("https://www.bcci.tv/")
driver.implicitly_wait(10)

page = driver.find_element_by_xpath("//a[@class='navigation__link navigation__link--in-drop-down']")  
search = page.get_attribute('href')

driver.get(search)

In [5]:
match_title=[]
series = []
place = []
date = []
time = []

for m in driver.find_elements_by_xpath('//strong[@class="fixture__name fixture__name--with-margin"]'):
    match_title.append(m.text)

for s in driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]'):
    series.append(s.text)
    
for p in driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/span'):
    place.append(p.text)

In [6]:
url=[]
for i in driver.find_elements_by_xpath('//div[@class="js-list"]/a'):
    url.append(i.get_attribute('href'))

In [7]:
for i in url:
    driver.get(i)
    d=driver.find_element_by_xpath('//div[@class="mc-header-scorebox__datetime"]/strong')
    date.append(d.text)
    
    t=driver.find_element_by_xpath('//span[@class="mc-header-scorebox__ist-time"]')
    time.append(t.text)

In [8]:
driver.close()

In [9]:
matches = pd.DataFrame()
matches['Match title']=match_title
matches['Series']=series
matches['Place']=place
matches['Date']=date
matches['Time']=time

matches.index = np.arange(1,len(matches)+1)
matches

,Match title,Series,Place,Date,Time
1,1st ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",Sunday 18 July,14:30 IST
2,2nd ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",Tuesday 20 July,14:30 IST
3,3rd ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",Friday 23 July,14:30 IST
4,1st T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",Sunday 25 July,19:00 IST
5,2nd T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",Tuesday 27 July,19:00 IST
6,3rd T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",Thursday 29 July,19:00 IST
7,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",Wednesday 4 August,15:30 IST
8,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",Thursday 12 August,15:30 IST
9,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",Wednesday 25 August,15:30 IST
10,4th Test,ENGLAND V INDIA 2021,"The Oval, London",Thursday 2 September,15:30 IST
11,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",Friday 10 September,15:30 IST

3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/
You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [10]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get("https://www.guru99.com/")
driver.implicitly_wait(10)

driver.find_element_by_id("gsc-i-id2").send_keys("selenium exception handling ")
driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button").click() 

page=driver.find_element_by_xpath("//a[@class='gs-title']")
link=page.get_attribute("data-ctorig")
driver.close()

In [11]:
res = requests.get(link)
soup = bs(res.text,'html.parser')

table = pd.read_html(res.text)
exception_handling=table[0]

In [12]:
exception_handling.columns=['Name','Description']
exception_handling.drop(exception_handling.index[[0]], inplace=True)
exception_handling

,Name,Description
1,ElementNotVisibleException,This type of Selenium exception occurs when an...
2,ElementNotSelectableException,This Selenium exception occurs when an element...
3,NoSuchElementException,This Exception occurs if an element could not ...
4,NoSuchFrameException,This Exception occurs if the frame target to b...
5,NoAlertPresentException,This Exception occurs when you switch to no pr...
6,NoSuchWindowException,This Exception occurs if the window target to ...
7,StaleElementReferenceException,This Selenium exception occurs happens when th...
8,SessionNotFoundException,The WebDriver is acting after you quit the bro...
9,TimeoutException,Thrown when there is not enough time for a com...
10,WebDriverException,This Exception takes place when the WebDriver ...
11,ConnectionClosedException,This type of Exception takes place when there ...
12,ElementClickInterceptedException,The command may not be completed as the elemen...
13,ElementNotInteractableException,This Selenium exception is thrown when any ele...
14,ErrorInResponseException,This happens while interacting with the Firefo...
15,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
16,ImeActivationFailedException,This expectation will occur when IME engine ac...
17,ImeNotAvailableException,It takes place when IME support is unavailable.
18,InsecureCertificateException,Navigation made the user agent to hit a certif...
19,InvalidArgumentException,It occurs when an argument does not belong to ...
20,InvalidCookieDomainException,This happens when you try to add a cookie unde...
21,InvalidCoordinatesException,This type of Exception matches an interacting ...
22,InvalidElementStateExceptio,It occurs when command can't be finished when ...
23,InvalidSessionIdException,This Exception took place when the given sessi...
24,InvalidSwitchToTargetException,This occurs when the frame or window target to...
25,JavascriptException,This issue occurs while executing JavaScript g...
26,JsonException,It occurs when you afford to get the session w...
27,NoSuchAttributeException,This kind of Exception occurs when the attribu...
28,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
29,NoSuchContextException,ContextAware does mobile device testing.
30,NoSuchCookieException,This Exception occurs when no cookie matching ...
31,NotFoundException,This Exception is a subclass of WebDriverExcep...
32,RemoteDriverServerException,This Selenium exception is thrown when the ser...
33,ScreenshotException,It is not possible to capture a screen.
34,SessionNotCreatedException,It happens when a new session could not be suc...
35,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
36,UnexpectedTagNameException,Happens if a support class did not get a web e...
37,UnhandledAlertException,This expectation occurs when there is an alert...
38,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
39,UnknownMethodException,This Exception happens when the requested comm...
40,UnreachableBrowserException,This Exception occurs only when the browser is...
41,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/
You have to find following details:

A) Rank

B) State

C) GSDP at current price (19-20)

D) GSDP at current price (18-19)

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [14]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get(" http://statisticstimes.com/ ")
driver.implicitly_wait(5)

In [15]:
ind = driver.find_element_by_xpath('//div[@class="dropdown-content"]/a[3]')
url=ind.get_attribute('href')

In [16]:
driver.get(url)

In [ ]:
gdp = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')  
gdp_url=gdp.get_attribute('href')

In [ ]:
driver.get(gdp_url)

In [18]:
table_url = driver.current_url

In [19]:
driver.close()
table_url

'http://statisticstimes.com/economy/india/indian-states-gdp.php'

In [11]:
res=requests.get(table_url)
df = pd.read_html(res.text)
df=df[1]
df

    Rank                      State GSDP (Cr INR at Current prices)            \
    Rank                      State                           19-20     18-19
0    1.0                Maharashtra                               -   2632792
1    2.0                 Tamil Nadu                         1845853   1630208
2    3.0              Uttar Pradesh                         1687818   1584764
3    4.0                    Gujarat                               -   1502899
4    5.0                  Karnataka                         1631977   1493127
5    6.0                West Bengal                         1253832   1089898
6    7.0                  Rajasthan                         1020989    942586
7    8.0             Andhra Pradesh                          972782    862957
8    9.0                  Telangana                          969604    861031
9   10.0             Madhya Pradesh                          906672    809592
10  11.0                     Kerala                               -    781653
11  12.0                      Delhi                          856112    774870
12  13.0                    Haryana                          831610    734163
13  14.0                      Bihar                          611804    530363
14  15.0                     Punjab                          574760    526376
15  16.0                     Odisha                          521275    487805
16  17.0                      Assam                               -    315881
17  18.0               Chhattisgarh                          329180    304063
18  19.0                  Jharkhand                          328598    297204
19  20.0                Uttarakhand                               -    245895
20  21.0            Jammu & Kashmir                               -    155956
21  22.0           Himachal Pradesh                          165472    153845
22  23.0                        Goa                           80449     73170
23  24.0                    Tripura                           55984     49845
24  25.0                 Chandigarh                               -     42114
25  26.0                 Puducherry                           38253     34433
26  27.0                  Meghalaya                           36572     33481
27  28.0                     Sikkim                           32496     28723
28  29.0                    Manipur                           31790     27870
29  30.0                   Nagaland                               -     27283
30  31.0          Arunachal Pradesh                               -     24603
31  32.0                    Mizoram                           26503     22287
32  33.0  Andaman & Nicobar Islands                               -         -
33   NaN                      India                        20351013  18886957

     Share GDP ($billion) GSDP (Cr INR at 2011-12 prices)
     18-19           2019                           19-20     18-19
0   13.94%        399.921                               -   2039074
1    8.63%        247.629                         1312929   1215307
2    8.39%        240.726                         1166817   1123982
3    7.96%        228.290                               -   1186379
4    7.91%        226.806                         1156039   1091077
5    5.77%        165.556                          793223    739525
6    4.99%        143.179                          711627    677428
7    4.57%        131.083                          672018    621301
8    4.56%        130.791                          663258    612828
9    4.29%        122.977                          561801    522009
10   4.14%        118.733                               -    559412
11   4.10%        117.703                          634408    590569
12   3.89%        111.519                          572240    531085
13   2.81%         80.562                          414977    375651
14   2.79%         79.957                          418868    397669
15   2.58%         74.098                          396499    376877
16   1.67%         47.982                               -    234048
17   1.61%         46.187                          243477    231182
18   1.57%         45.145                          240036    224986
19   1.30%         37.351                               -    193273
20   0.83%         23.690                               -    112755
21   0.81%         23.369                          124403    117851
22   0.39%         11.115                           63408     57787
23   0.26%          7.571                           40583     36963
24   0.22%          6.397                               -     31192
25   0.18%          5.230                           25093     23013
26   0.18%          5.086                           26695     24682
27   0.15%          4.363                           20017     18722
28   0.15%          4.233                           20673     19300
29   0.14%          4.144                               -     17647
30   0.13%          3.737                               -     16676
31   0.12%          3.385                           18797     16478
32       -              -                               -         -
33     NaN           2869                        14569268  14003316

 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/
You have to find the following details:
    
A) Repository title

B) Repository description 

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [153]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get(" https://github.com/")
driver.implicitly_wait(5)

In [154]:
driver.find_element_by_xpath('//div[@class="position-relative mr-3"]').click()
driver.find_element_by_xpath("//input[@name='login']").send_keys("mishra-31")
driver.find_element_by_xpath("//input[@name='password']").send_keys("xxxxxxxxxxx")
driver.find_element_by_xpath("//input[@name='commit']").click()
driver.find_element_by_xpath("/html/body/div[1]/header/div[3]/nav/a[4]").click()
driver.find_element_by_xpath('//*[@id="js-pjax-container"]/div[1]/nav/div/a[3]').click()

In [155]:
url = []
for i in driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]/a'):
    url.append(i.get_attribute('href'))

In [156]:
repository_title = []
repository_description = []
contributors_count = []
language_used = []
for i in url:
    driver.get(i)
    driver.implicitly_wait(3)
    
    try:
        title = driver.find_element_by_xpath('//strong[@itemprop="name"]/a')
        repository_title.append(title.text)
    except NoSuchElementException:
        repository_title.append('-')
        
        
    try:
        description = driver.find_element_by_xpath('//p[@class="f4 mt-3"]')
        repository_description.append(description.text)
    except NoSuchElementException:
        repository_description.append('-')
        
    
    try:
        contributors = driver.find_element_by_xpath('//h2[@class="h4 mb-3"]/a[contains(text(),"Contributors")]/span')    
        contributors_count.append(contributors.text)
    except:
        contributors_count.append('-')
        
    l=[]
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:
        for i in languages:
            l.append(i.text)
    else:
        l.append("No languages used")
    language_used.append(l)

In [157]:
driver.close()

github = pd.DataFrame()
github['Repository']=repository_title
github['Description']=repository_description
github['No of contributors']=contributors_count
github['Languages used']=language_used

github.index=np.arange(1,len(github)+1)
github

,Repository,Description,No of contributors,Languages used
1,wifi-card,📶 Print a QR code for connecting to your WiFi,7,"[JavaScript, HTML, CSS, Makefile, Dockerfile]"
2,folly,An open-source C++ library developed and used ...,580,"[C++, Python, CMake, C, Shell, Assembly]"
3,IoT-For-Beginners,"12 Weeks, 24 Lessons, IoT for All!",26,"[C++, Python, C, Jupyter Notebook, Vue, HTML, ..."
4,ghidra,Ghidra is a software reverse engineering (SRE)...,149,"[Java, C++, HTML, C, Python, Shell]"
5,CBL-Mariner,Linux OS for Azure 1P services and edge applia...,37,"[Go, Shell, C, Makefile, Roff, Python]"
6,OpenSearch,Open source distributed and RESTful search eng...,46,"[Java, Groovy, Shell, Batchfile, ANTLR, Docker..."
7,awesome-go,"A curated list of awesome Go frameworks, libra...","1,489",[Go]
8,awesome-fenix,讨论如何构建一套可靠的大型分布式系统,8,"[Vue, JavaScript, Stylus, Shell]"
9,Sa-Token,这可能是史上功能最全的Java权限认证框架！目前已集成——登录认证、权限认证、分布式Sess...,20,"[Java, HTML, CSS]"
10,wtf,"wtf is a distributed, code-coverage guided, cu...",2,"[C++, Assembly, Rust, Python, C, CMake]"
11,GFPGAN,-,-,[Python]
12,ML-For-Beginners,"12 weeks, 24 lessons, classic Machine Learning...",35,[Jupyter Notebook]
13,algorithm-base,专门为刚开始刷题的同学准备的算法基地，没有最细只有更细，立志用动画将晦涩难懂的算法说的通俗易懂！,6,[Java]
14,PaddleSeg,End-to-end image segmentation kit based on Pad...,47,"[Python, Java, C++, CMake, Dockerfile, Shell]"
15,WechatDecrypt,微信消息解密工具,-,[C++]
16,awesome-mac," Now we have become very big, Different from ...",358,[JavaScript]
17,GitHub-Chinese-Top-Charts,🇨🇳 GitHub中文排行榜，帮助你发现高分优秀中文项目、更高效地吸收国人的优秀经验成果；榜...,-,[Java]
18,facebook-ios-sdk,Used to integrate the Facebook Platform with y...,117,"[Objective-C, Swift, Objective-C++, Shell, Rub..."
19,kratos,A Go framework for microservices.,104,"[Go, Makefile]"
20,bat,A cat(1) clone with wings.,236,"[Rust, Python]"
21,sync,-,-,[No languages used]
22,The-Complete-FAANG-Preparation,This repository contains all the DSA (Data-Str...,33,"[Jupyter Notebook, Python, C++, JavaScript, Ja..."
23,mesh-transformer-jax,Model parallel transformers in JAX and Haiku,11,"[Python, Jupyter Notebook, Shell, Dockerfile]"
24,scripts,-,-,[JavaScript]
25,milvus,An open source vector database powered by Fais...,142,"[Go, C++, Python, CMake, Shell, C]"

6. Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/
You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [42]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get("https://www.billboard.com/")
driver.implicitly_wait(5)

In [43]:
driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/nav/ul/li[3]/a').click()

In [44]:
song=[]
artist=[]
lw_rank=[]
peak_rank=[]
wks_on_brd = []

In [45]:
for i in driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]'):
    song.append(i.text)

In [46]:
for i in driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]'):
    artist.append(i.text)

In [47]:
for i in driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]'):  
    lw_rank.append(i.text)

In [48]:
for i in driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]'):  
    peak_rank.append(i.text)

In [49]:
for i in driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]'):  
    wks_on_brd.append(i.text)

In [50]:
driver.close()

billboard = pd.DataFrame()
billboard['Song']=song
billboard['Artist']=artist
billboard['Last week rank']=lw_rank
billboard['Peak Rank']=peak_rank
billboard['Weeks on board']=wks_on_brd

billboard.index=np.arange(1,len(billboard)+1)
billboard

,Song,Artist,Last week rank,Peak Rank,Weeks on board
1,Butter,BTS,1,1,7
2,Good 4 U,Olivia Rodrigo,2,1,8
3,Levitating,Dua Lipa Featuring DaBaby,4,2,40
4,Kiss Me More,Doja Cat Featuring SZA,3,3,13
5,Montero (Call Me By Your Name),Lil Nas X,8,1,15
...,...,...,...,...,...
96,All I Know So Far,P!nk,-,74,4
97,What's Next,Drake,-,1,16
98,Enough For You,Olivia Rodrigo,-,14,6
99,Juggernaut,"Tyler, The Creator Featuring Lil Uzi Vert & Ph...",40,40,2
100,Tell Em,Cochise & $NOT,-,64,4

7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/
You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [189]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get("https://www.naukri.com/")
driver.implicitly_wait(10)

In [190]:
recruiter=driver.find_element_by_xpath('//a[@title="Search Recruiters"]')
recruiter_button=recruiter.get_attribute('href')
driver.get(recruiter_button)
driver.find_element_by_xpath('//input[@class="sugInp"]').send_keys("Data Science")
driver.find_element_by_id('qsbFormBtn').click()

In [197]:
name=[]
designation=[]
company=[]
skills=[]
location=[]

In [198]:
for i in driver.find_elements_by_xpath('//span[@class="fl ellipsis"]'):
    name.append(i.text)
name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Ruchi Dhote',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Azahar Shaikh',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Priya Khare',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'SREEDHAR',
 'Radha Manivasagam',
 'Prateek Kumar',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury',
 'Shailja Mishra',
 'Sunny Sharma']

In [199]:
for i in driver.find_elements_by_xpath('//span[@class="ellipsis clr"]'):
    designation.append(i.text)
designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'Senior Executive Talent Acquisition',
 'HR Team Lead',
 'HR Manager',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'Company Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Senior Manager',
 'Company Recruitment Head',
 'Project Manager',
 'Recruitment Consultant',
 'HR Executive',
 'Head',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner',
 'HR Manager',
 'Managing Director - HR']

In [200]:
for i in driver.find_elements_by_xpath('//a[@class="ellipsis"][2]'):
    company.append(i.text)

In [201]:
company

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Bristlecone India Ltd',
 'SocialPrachar.com',
 'BISP Solutions',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Independent Consultant',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED',
 'Techcovery',
 'Trisect',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai',
 'Certybox Pvt.Ltd.',
 'Western Service Providers']

In [202]:
for i in driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]'):
    skills.append(i.text)
skills

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All',
 'Python, Artificial Intelligence, Machine Learning, Data Science',
 'Java, Python, Angularjs, Software Testing, Machine Learning, Data Science, Javascript, Django, React.js, Node.js, Augmented Reality, Virtual Reality, Advanced',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing',
 'consulting, Education Counseling, Educational Sales, Institutional Sales, pmp, Data Science, Business Development, Revenue Generation, Sales Achievement, new',
 'Software Professionals, Engineering, Technical Management, Financial Management, Human Resource Management, Banking, Google Adwords, Business Analysis, It']

In [186]:
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='ellipsis']"):
    urls.append(i.get_attribute("href"))

In [187]:
for i in urls:
    driver.get(i)
    try:
        loc=driver.find_element_by_xpath("//div[@class='oh'][2]//a")
        location.append(loc.text)
    except NoSuchElementException:
        location.append('-')
Location=location[::2]

In [204]:
Location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Others',
 'Delhi',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Noida',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 '',
 'Noida',
 'Mumbai']

In [203]:
driver.close()


recruiters = pd.DataFrame()
recruiters['Name']=name
recruiters['Designation']=designation
recruiters['Company']=company
recruiters['Skills they hire for']=skills
recruiters['Location']=Location

recruiters.index = np.arange(1,len(recruiters)+1)
recruiters

,Name,Designation,Company,Skills they hire for,Location
1,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
2,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
3,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
4,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
18,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
19,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
20,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
21,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
22,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
25,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
26,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
27,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
28,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
29,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
32,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
33,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
34,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",
49,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational ...",Noida
50,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals, Engineering, Technical...",Mumbai

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/
You have to find the following details:
    
A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [52]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"    
content = requests.get(url)
df = pd.read_html(content.text)

In [53]:
books = df[0]
books

,Rank,Title,Author,Volume Sales,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan",5094805,Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.",4475152,Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",4200654,Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",4179479,Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.",3758936,Random House,Romance & Sagas
...,...,...,...,...,...,...
96,97,Happy Days with the Naked Chef,"Oliver, Jamie",794201,Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",792187,Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",791507,Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",791095,Penguin,Food & Drink: General
100,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN,SOURCE: NIELSEN BOOK SCAN

9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/
You have to find the following details: 

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [56]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get("https://www.imdb.com/list/ls095964455/")
driver.implicitly_wait(10)

In [57]:
name=[]
year=[]
genre=[]
run_time=[]
ratings=[]
votes=[]

In [58]:
for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a'):
    name.append(i.text)

In [59]:
for i in driver.find_elements_by_xpath('//span[@class="lister-item-year text-muted unbold"]'):
    year.append(i.text)

In [60]:
for i in driver.find_elements_by_xpath('//span[@class="genre"]'):
    genre.append(i.text)

In [61]:
for i in driver.find_elements_by_xpath('//span[@class="runtime"]'):
    run_time.append(i.text)

In [62]:
for i in driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]'):
    ratings.append(i.text)

In [63]:
for i in driver.find_elements_by_xpath('//span[@name="nv"]'):
    votes.append(i.text)

In [65]:
driver.close()

imdb = pd.DataFrame()
imdb["Name"]=name
imdb["Year Span"]=year
imdb["Genre"]=genre
imdb["Runtime"]=run_time
imdb["Ratings"]=ratings
imdb["Vote"]=votes

imdb.index = np.arange(1,len(imdb)+1)
imdb

,Name,Year Span,Genre,Runtime,Ratings,Vote
1,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,835,393"
2,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"874,161"
3,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"879,319"
4,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"264,212"
5,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"225,709"
...,...,...,...,...,...,...
96,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,790"
97,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,397"
98,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"169,584"
99,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,120"
100,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"193,351"

10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/
You have to find the following details:
    
A) Dataset name

B) Data type

C) Task

D) Attribute type 

E) No of instances

F) No of attribute 

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

In [136]:
driver = webdriver.Chrome('/Users/abhishekmishra/chromedriver')
driver.maximize_window()
driver.get("https://archive.ics.uci.edu/ml/index.php")
driver.implicitly_wait(10)

In [141]:
datasets=driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a')
dataset_url=datasets.get_attribute('href')
dataset_url

'https://archive.ics.uci.edu/ml/datasets.php'

In [143]:
driver.get(dataset_url)

In [145]:
url = driver.current_url
url

'https://archive.ics.uci.edu/ml/datasets.php'

In [148]:
res = requests.get(url)
table = pd.read_html(res.text)
table

[                                                   0  \
 0  Center for Machine Learning and Intelligent Sy...

                                                    1
 0  About Citation Policy Donate a Data Set Contac...  ,
                                                    0  \
 0  Browse Through:  Default Task Classification (...

                                                    1
 0  588 Data Sets  Table View List View  Name  Dat...  ,
                  0
 0  Browse Through:,
                                                     0
 0                                        Default Task
 1   Classification (442)Regression (137)Clustering...
 2                                      Attribute Type
 3           Categorical (38)Numerical (396)Mixed (55)
 4                                           Data Type
 5   Multivariate (456)Univariate (27)Sequential (5...
 6                                                Area
 7   Life Sciences (138)Physical Sciences (57)CS / ...
 8                                        # Attributes
 9   Less than 10 (151)10 to 100 (266)Greater than ...
 10                                        # Instances
 11  Less than 100 (36)100 to 1000 (199)Greater tha...
 12                                        Format Type
 13                       Matrix (411)Non-Matrix (177),
                0                     1
 0  588 Data Sets  Table View List View,
                                     0             1                    2  \
 0                                Name    Data Types         Default Task
 1                             Abalone  Multivariate       Classification
 2                               Adult  Multivariate       Classification
 3                           Annealing  Multivariate       Classification
 4        Anonymous Microsoft Web Data           NaN  Recommender-Systems
 ..                                ...           ...                  ...
 584  in-vehicle coupon recommendation  Multivariate       Classification
 585               Gait Classification  Multivariate       Classification
 586         Wikipedia Math Essentials   Time-Series           Regression
 587         Wikipedia Math Essentials   Time-Series           Regression
 588      Synchronous Machine Data Set  Multivariate           Regression

                               3            4             5     6
 0               Attribute Types  # Instances  # Attributes  Year
 1    Categorical, Integer, Real         4177             8  1995
 2          Categorical, Integer        48842            14  1996
 3    Categorical, Integer, Real          798            38   NaN
 4                   Categorical        37711           294  1998
 ..                          ...          ...           ...   ...
 584                         NaN        12684            23  2020
 585                        Real           48           321  2020
 586                        Real          731          1068  2021
 587                        Real          731          1068  2021
 588                        Real          557             5  2021

 [589 rows x 7 columns],
     0        1
 0 NaN  Abalone,
     0      1
 0 NaN  Adult,
     0          1
 0 NaN  Annealing,
     0                             1
 0 NaN  Anonymous Microsoft Web Data,
     0           1
 0 NaN  Arrhythmia,
     0                      1
 0 NaN  Artificial Characters,
     0                     1
 0 NaN  Audiology (Original),
     0                         1
 0 NaN  Audiology (Standardized),
     0         1
 0 NaN  Auto MPG,
     0           1
 0 NaN  Automobile,
     0       1
 0 NaN  Badges,
     0              1
 0 NaN  Balance Scale,
     0         1
 0 NaN  Balloons,
     0              1
 0 NaN  Breast Cancer,
     0                                   1
 0 NaN  Breast Cancer Wisconsin (Original),
     0                                     1
 0 NaN  Breast Cancer Wisconsin (Prognostic),
     0                                     1
 0 NaN  Breast Cancer Wisconsin (Diagnostic),
     0                   1
 0 NaN  Pittsburgh Bridges,
     0               1
 0 NaN  Car Evaluation,
     0              1
 0 NaN  Census Income,
     0                                  1
 0 NaN  Chess (King-Rook vs. King-Knight),
     0                                1
 0 NaN  Chess (King-Rook vs. King-Pawn),
     0                           1
 0 NaN  Chess (King-Rook vs. King),
     0                        1
 0 NaN  Chess (Domain Theories),
     0              1
 0 NaN  Bach Chorales,
     0          1
 0 NaN  Connect-4,
     0                1
 0 NaN  Credit Approval,
     0                          1
 0 NaN  Japanese Credit Screening,
     0                  1
 0 NaN  Computer Hardware,
     0                            1
 0 NaN  Contraceptive Method Choice,
     0          1
 0 NaN  Covertype,
     0               1
 0 NaN  Cylinder Bands,
     0            1
 0 NaN  Dermatology,
     0         1
 0 NaN  Diabetes,
     0                                          1
 0 NaN  DGP2 - The Second Data Generation Program,
     0                       1
 0 NaN  Document Understanding,
     0                    1
 0 NaN  EBL Domain Theories,
     0               1
 0 NaN  Echocardiogram,
     0      1
 0 NaN  Ecoli,
     0      1
 0 NaN  Flags,
     0                 1
 0 NaN  Function Finding,
     0                     1
 0 NaN  Glass Identification,
     0                    1
 0 NaN  Haberman's Survival,
     0           1
 0 NaN  Hayes-Roth,
     0              1
 0 NaN  Heart Disease,
     0          1
 0 NaN  Hepatitis,
     0            1
 0 NaN  Horse Colic,
     0    1
 0 NaN  ICU,
     0                   1
 0 NaN  Image Segmentation,
     0                        1
 0 NaN  Internet Advertisements,
     0           1
 0 NaN  Ionosphere,
     0     1
 0 NaN  Iris,
     0       1
 0 NaN  ISOLET,
     0        1
 0 NaN  Kinship,
     0                1
 0 NaN  Labor Relations,
     0                   1
 0 NaN  LED Display Domain,
     0       1
 0 NaN  Lenses,
     0                   1
 0 NaN  Letter Recognition,
     0                1
 0 NaN  Liver Disorders,
     0               1
 0 NaN  Logic Theorist,
     0            1
 0 NaN  Lung Cancer,
     0             1
 0 NaN  Lymphography,
     0                    1
 0 NaN  Mechanical Analysis,
     0          1
 0 NaN  Meta-data,
     0              1
 0 NaN  Mobile Robots,
     0                                            1
 0 NaN  Molecular Biology (Promoter Gene Sequences),
     0                                                1
 0 NaN  Molecular Biology (Protein Secondary Structure),
     0                                                  1
 0 NaN  Molecular Biology (Splice-junction Gene Sequen...,
     0                1
 0 NaN  MONK's Problems,
     0               1
 0 NaN  Moral Reasoner,
     0                  1
 0 NaN  Multiple Features,
     0         1
 0 NaN  Mushroom,
     0                 1
 0 NaN  Musk (Version 1),
     0                 1
 0 NaN  Musk (Version 2),
     0        1
 0 NaN  Nursery,
     0                      1
 0 NaN  Othello Domain Theory,
     0                           1
 0 NaN  Page Blocks Classification,
     0                                          1
 0 NaN  Optical Recognition of Handwritten Digits,
     0                                            1
 0 NaN  Pen-Based Recognition of Handwritten Digits,
     0                       1
 0 NaN  Post-Operative Patient,
     0              1
 0 NaN  Primary Tumor,
     0        1
 0 NaN  Prodigy,
     0                                             1
 0 NaN  Qualitative Structure Activity Relationships,
     0                  1
 0 NaN  Quadruped Mammals,
     0      1
 0 NaN  Servo,
     0                        1
 0 NaN  Shuttle Landing Control,
     0            1
 0 NaN  Solar Flare,
     0                1
 0 NaN  Soybean (Large),
     0                1
 0 NaN  Soybean (Small),
     0                                    1
 0 NaN  Challenger USA Space Shuttle O-Ring,
     0                            1
 0 NaN  Low Resolution Spectrometer,
     0         1
 0 NaN  Spambase,
     0            1
 0 NaN  SPECT Heart,
     0             1
 0 NaN  SPECTF Heart,
     0       1
 0 NaN  Sponge,
     0                1
 0 NaN  Statlog Project,
     0                        1
 0 NaN  Student Loan Relational,
     0                              1
 0 NaN  Teaching Assistant Evaluation,
     0                    1
 0 NaN  Tic-Tac-Toe Endgame,
     0                1
 0 NaN  Thyroid Disease,
     0       1
 0 NaN  Trains,
     0           1
 0 NaN  University,
     0                             1
 0 NaN  Congressional Voting Records,
     0                      1
 0 NaN  Water Treatment Plant,
     0                                        1
 0 NaN  Waveform Database Generator (Version 1),
     0                                        1
 0 NaN  Waveform Database Generator (Version 2),
     0     1
 0 NaN  Wine,
     0      1
 0 NaN  Yeast,
     0    1
 0 NaN  Zoo,
     0             1
 0 NaN  Undocumented,
     0                  1
 0 NaN  Twenty Newsgroups,
     0                               1
 0 NaN  Australian Sign Language signs,
     0                                              1
 0 NaN  Australian Sign Language signs (High Quality),
     0                      1
 0 NaN  US Census Data (1990),
     0                    1
 0 NaN  Census-Income (KDD),
     0                           1
 0 NaN  Coil 1999 Competition Data,
     0                     1
 0 NaN  Corel Image Features,
     0              1
 0 NaN  E. Coli Genes,
     0             1
 0 NaN  EEG Database,
     0        1
 0 NaN  El Nino,
     0                                   1
 0 NaN  Entree Chicago Recommendation Data,
     0                1
 0 NaN  CMU Face Images,
     0                                        1
 0 NaN  Insurance Company Benchmark (COIL 2000),
     0                    1
 0 NaN  Internet Usage Data,
     0                      1
 0 NaN  IPUMS Census Database,
     0                1
 0 NaN  Japanese Vowels,
     0                  1
 0 NaN  KDD Cup 1998 Data,
     0                  1
 0 NaN  KDD Cup 1999 Data,
     0                      1
 0 NaN  M. Tuberculosis Genes,
     0      1
 0 NaN  Movie,
     0                             1
 0 NaN  MSNBC.com Anonymous Web Data,
     0                                       1
 0 NaN  NSF Research Award Abstracts 1990-2003,
     0                            1
 0 NaN  Pioneer-1 Mobile Robot Data,
     0                                      1
 0 NaN  Pseudo Periodic Synthetic Time Series,
     0                                             1
 0 NaN  Reuters-21578 Text Categorization Collection,
     0                         1
 0 NaN  Robot Execution Failures,
     0                                    1
 0 NaN  Synthetic Control Chart Time Series,
     0                                    1
 0 NaN  Syskill and Webert Web Page Ratings,
     0               1
 0 NaN  UNIX User Data,
     0                                        1
 0 NaN  Volcanoes on Venus - JARtool experiment,
     0                                     1
 0 NaN  Statlog (Australian Credit Approval),
     0                             1
 0 NaN  Statlog (German Credit Data),
     0                1
 0 NaN  Statlog (Heart),
     0                            1
 0 NaN  Statlog (Landsat Satellite),
     0                             1
 0 NaN  Statlog (Image Segmentation),
     0                  1
 0 NaN  Statlog (Shuttle),
     0                              1
 0 NaN  Statlog (Vehicle Silhouettes),
     0                                     1
 0 NaN  Connectionist Bench (Nettalk Corpus),
     0                                             1
 0 NaN  Connectionist Bench (Sonar, Mines vs. Rocks),
     0                                                  1
 0 NaN  Connectionist Bench (Vowel Recognition - Deter...,
     0                   1
 0 NaN  Economic Sanctions,
     0             1
 0 NaN  Protein Data,
     0      1
 0 NaN  Cloud,
     0                              1
 0 NaN  CalIt2 Building People Counts,
     0                    1
 0 NaN  Dodgers Loop Sensor,
     0           1
 0 NaN  Poker Hand,
     0                      1
 0 NaN  MAGIC Gamma Telescope,
     0                   1
 0 NaN  UJI Pen Characters,
     0                  1
 0 NaN  Mammographic Mass,
     0             1
 0 NaN  Forest Fires,
     0                           1
 0 NaN  Reuters Transcribed Subset,
     0             1
 0 NaN  Bag of Words,
     0                              1
 0 NaN  Concrete Compressive Strength,
     0            1
 0 NaN  Hill-Valley,
     0       1
 0 NaN  Arcene,
     0       1
 0 NaN  Dexter,
     0         1
 0 NaN  Dorothea,
     0        1
 0 NaN  Gisette,
     0        1
 0 NaN  Madelon,
     0                      1
 0 NaN  Ozone Level Detection,
     0                                1
 0 NaN  Abscisic Acid Signaling Network,
     0           1
 0 NaN  Parkinsons,
     0                       1
 0 NaN  Character Trajectories,
     0                                 1
 0 NaN  Blood Transfusion Service Center,
     0                               1
 0 NaN  UJI Pen Characters (Version 2),
     0                          1
 0 NaN  Semeion Handwritten Digit,
     0      1
 0 NaN  SECOM,
     0       1
 0 NaN  Plants,
     0                1
 0 NaN  Libras Movement,
     0                    1
 0 NaN  Concrete Slump Test,
     0                      1
 0 NaN  Communities and Crime,
     0                    1
 0 NaN  Acute Inflammations,
     0             1
 0 NaN  Wine Quality,
     0               1
 0 NaN  URL Reputation,
     0            1
 0 NaN  p53 Mutants,
     0                          1
 0 NaN  Parkinsons Telemonitoring,
     0             1
 0 NaN  Demospongiae,
     0                          1
 0 NaN  Opinosis Opinion ⁄ Review,
     0              1
 0 NaN  Breast Tissue,
     0                 1
 0 NaN  Cardiotocography,
     0                                     1
 0 NaN  Wall-Following Robot Navigation Data,
     0                    1
 0 NaN  Spoken Arabic Digit,
     0                                      1
 0 NaN  Localization Data for Person Activity,
     0         1
 0 NaN  AutoUniv,
     0                    1
 0 NaN  Steel Plates Faults,
     0                                  1
 0 NaN  MiniBooNE particle identification,
     0                  1
 0 NaN  YearPredictionMSD,
     0        1
 0 NaN  PEMS-SF,
     0                        1
 0 NaN  OpinRank Review Dataset,
     0                                             1
 0 NaN  Relative location of CT slices on axial axis,
     0                                               1
 0 NaN  Online Handwritten Assamese Characters Dataset,
     0                      1
 0 NaN  PubChem Bioassay Data,
     0                                   1
 0 NaN  Record Linkage Comparison Patterns,
     0                                   1
 0 NaN  Communities and Crime Unnormalized,
     0                 1
 0 NaN  Vertebral Column,
     0                             1
 0 NaN  EMG Physical Action Data Set,
     0                               1
 0 NaN  Vicon Physical Action Data Set,
     0                            1
 0 NaN  Amazon Commerce reviews set,
     0                      1
 0 NaN  Amazon Access Samples,
     0             1
 0 NaN  Reuter_50_50,
     0         1
 0 NaN  Farm Ads,
     0                1
 0 NaN  DBWorld e-mails,
     0                                           1
 0 NaN  KEGG Metabolic Relation Network (Directed),
     0                                             1
 0 NaN  KEGG Metabolic Reaction Network (Undirected),
     0               1
 0 NaN  Bank Marketing,
     0                                    1
 0 NaN  YouTube Comedy Slam Preference Data,
     0                               1
 0 NaN  Gas Sensor Array Drift Dataset,
     0                                    1
 0 NaN  ILPD (Indian Liver Patient Dataset),
     0                                 1
 0 NaN  OPPORTUNITY Activity Recognition,
     0      1
 0 NaN  Nomao,
     0                    1
 0 NaN  SMS Spam Collection,
     0                  1
 0 NaN  Skin Segmentation,
     0               1
 0 NaN  Planning Relax,
     0                                    1
 0 NaN  PAMAP2 Physical Activity Monitoring,
     0                           1
 0 NaN  Restaurant & consumer data,
     0       1
 0 NaN  CNAE-9,
     0                                                1
 0 NaN  Individual household electric power consumption,
     0      1
 0 NaN  seeds,
     0        1
 0 NaN  Northix,
     0               1
 0 NaN  QtyT40I10D100K,
     0                   1
 0 NaN  Legal Case Reports,
     0                                             1
 0 NaN  Human Activity Recognition Using Smartphones,
     0                                          1
 0 NaN  One-hundred plant species leaves data set,
     0                  1
 0 NaN  Energy efficiency,
     0                    1
 0 NaN  Yacht Hydrodynamics,
     0          1
 0 NaN  Fertility,
     0                         1
 0 NaN  Daphnet Freezing of Gait,
     0                                         1
 0 NaN  3D Road Network (North Jutland, Denmark),
     0                        1
 0 NaN  ISTANBUL STOCK EXCHANGE,
     0                     1
 0 NaN  Buzz in social media,
     0                            1
 0 NaN  First-order theorem proving,
     0                                                  1
 0 NaN  Wearable Computing: Classification of Body Pos...,
     0                                            1
 0 NaN  Gas sensor arrays in open sampling settings,
     0                                 1
 0 NaN  Climate Model Simulation Crashes,
     0          1
 0 NaN  MicroMass,
     0                    1
 0 NaN  QSAR biodegradation,
     0        1
 0 NaN  BLOGGER,
     0                            1
 0 NaN  Daily and Sports Activities,
     0                        1
 0 NaN  User Knowledge Modeling,
     0                                                  1
 0 NaN  Reuters RCV1 RCV2 Multilingual, Multiview Text...,
     0     1
 0 NaN  NYSK,
     0                           1
 0 NaN  Turkiye Student Evaluation,
     0                                                  1
 0 NaN  ser Knowledge Modeling Data (Students' Knowled...,
     0              1
 0 NaN  EEG Eye State,
     0                                                  1
 0 NaN  Physicochemical Properties of Protein Tertiary...,
     0              1
 0 NaN  seismic-bumps,
     0                        1
 0 NaN  banknote authentication,
     0                                                  1
 0 NaN  USPTO Algorithm Challenge, run by NASA-Harvard...,
     0                                      1
 0 NaN  YouTube Multiview Video Games Dataset,
     0                                                  1
 0 NaN  Gas Sensor Array Drift Dataset at Different Co...,
     0                                                  1
 0 NaN  Activities of Daily Living (ADLs) Recognition ...,
     0                                 1
 0 NaN  SkillCraft1 Master Table Dataset,
     0                                                  1
 0 NaN  Weight Lifting Exercises monitored with Inerti...,
     0        1
 0 NaN  SML2010,
     0                     1
 0 NaN  Bike Sharing Dataset,
     0                                                  1
 0 NaN  Predict keywords activities in a online social...,
     0                      1
 0 NaN  Thoracic Surgery Data,
     0                          1
 0 NaN  EMG dataset in Lower Limb,
     0     1
 0 NaN  SUSY,
     0      1
 0 NaN  HIGGS,
     0                       1
 0 NaN  Qualitative_Bankruptcy,
     0                          1
 0 NaN  LSVT Voice Rehabilitation,
     0                                                  1
 0 NaN  Dataset for ADL Recognition with Wrist-worn Ac...,
     0     1
 0 NaN  Wilt,
     0                                          1

In [150]:
details = table[5]
details.columns = ['Name','Data Types','Default Task','Attribute Types',
                   'No of instances','No of Attributes','Year']
details.drop(details.index[[0]], inplace=True)

In [152]:
details

,Name,Data Types,Default Task,Attribute Types,No of instances,No of Attributes,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,NaN
4,Anonymous Microsoft Web Data,NaN,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
584,in-vehicle coupon recommendation,Multivariate,Classification,NaN,12684,23,2020
585,Gait Classification,Multivariate,Classification,Real,48,321,2020
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
588,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021